### ISSUE TITLE
Can't handle the apollo registration request

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/tripal_apollo#105]
seen screenshot as below
![image.png](https://images.zenhubusercontent.com/5bbf72e419e5685bccf0e630/745bdf73-4978-452f-97d7-6c530cc76e9b)

encounter this issue after submitting apollo-registration

**Comment by bradfordcondon** [comment]
ok im confident this is related to the password generation.  deming created an empty dict file instead of populating it iwht words.  you MUST have words there or it will 500 error.

We should add a layer of checking and send an admin error log/return with error to prevent the 500 error though.

**Comment by bradfordcondon** [comment]
Heres how the issue is documented:

![screen shot 2018-11-12 at 3 50 21 pm](https://user-images.githubusercontent.com/7063154/48374386-ae60e700-e692-11e8-83d7-6a796b0f7f1f.png)

I'm going to upgrade this and stick it in a "warning" box to make it more explicit that your site breaks without this file.

**Comment by bradfordcondon** [comment]
![screen shot 2018-11-12 at 3 53 55 pm](https://user-images.githubusercontent.com/7063154/48374530-2d561f80-e693-11e8-97e8-2a7fa5c6bc62.png)
