### ISSUE TITLE
apollo group configuration

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#41]
the -group flag is required.  For apollo 2 it appears to be built by collecting the organism's full name and appending _WRITE and _USER.  It looks like it might be different for Apollo 1.

How should we handle groups here?

**Comment by bradfordcondon** [comment]
Thoughts for broad support:

* REGEXP to build group from the record label
* use API to pull in groups
* Set a "record to group" admin area that lets admins automatically map organism-level permissions to groups

@childers i imagine i'll need some input here, or perhaps im missing a facet of the issue.

**Comment by childers** [comment]
For Apollo 1 each species is it's own app and has no groups.

For Apollo2, we go as follows:
For each organism we set up three groups: Genus_species_WRITE, Genus_species_USER, and Genus_species_ADMIN.  the admin account has NO elevated permissions, and is there for us to tag the species coordinators.  The Genus_species_USER account has read permissions and the Genus_species_WRITE has READ and WRITE permissions set for that organism. This way we can assign permissions at the group level so we don't have to manage things per user.  Since annotatio windows are usually done by the whole group at once, this system should be fine.

**Comment by bradfordcondon** [comment]
thanks @childers 

That makes me think we should do the following:

Add users via `genus_species_[role]`.  Down the road we can try to add regexp/key support, or, full blown "configure the groups for this record" if other groups set up their groups differently.

**Comment by bradfordcondon** [comment]
implemented groups for apollo 2 as chris has suggested.  Leaving this issue open and recasting it as a discussion about future improvements to be more flexible for other group uses cases (other site configs, analysis/projects).
